# Colores
BLANCO = (255, 255, 255)
NEGRO = (0, 0, 0)
GRIS = (206, 206, 206)
AZUL = (30, 136, 229)

# Seteos Juego
ANCHO_PANTALLA = 800
ALTO_PANTALLA = 800
ALTO_TEXTO = 100

CANT_TARJETAS_H = 4
CANT_TARJETAS_V = 4
CANT_TOTAL_TARJETAS = int((CANT_TARJETAS_V * CANT_TARJETAS_H) / 2)

ANCHO_TARJETA = int(ANCHO_PANTALLA / CANT_TARJETAS_H)
ALTO_TARJETA = int((ALTO_PANTALLA - ALTO_TEXTO) / CANT_TARJETAS_V)

ANCHO_BOTON = 170
ALTO_BOTON = 100

# PATH_RECURSOS = r"../labo-progra_1/clase_16/recursos"
PATH_RECURSOS = r"../sin_POO/recursos"
